# Trabajo final

En primer lugar, se importan las librerías necesarias para realizar el trabajo.

In [1]:
import pandas as pd
import altair as alt

En seguida, se importa la base de datos que contiene información sobre la producción y consumo de energías renovables en los Estados Unidos. La información se puede descargar de la sección de energía renovables de la página web de U.S. Energy Information Administration (disponible en:https://www.eia.gov/totalenergy/data/monthly/).

In [2]:
RE=pd.read_csv("MER_T10_01.csv")
RE.head(10)

,MSN,YYYYMM,Value,Column_Order,Description,Unit
0,WDPRBUS,194913,1549.262,1,Wood Energy Production,Trillion Btu
1,WDPRBUS,195013,1562.307,1,Wood Energy Production,Trillion Btu
2,WDPRBUS,195113,1534.669,1,Wood Energy Production,Trillion Btu
3,WDPRBUS,195213,1474.369,1,Wood Energy Production,Trillion Btu
4,WDPRBUS,195313,1418.601,1,Wood Energy Production,Trillion Btu
5,WDPRBUS,195413,1394.327,1,Wood Energy Production,Trillion Btu
6,WDPRBUS,195513,1424.143,1,Wood Energy Production,Trillion Btu
7,WDPRBUS,195613,1415.871,1,Wood Energy Production,Trillion Btu
8,WDPRBUS,195713,1333.581,1,Wood Energy Production,Trillion Btu
9,WDPRBUS,195813,1323.123,1,Wood Energy Production,Trillion Btu

Generamos una copia de la base de datos, para realizar la limpieza de datos.

In [3]:
RE2=RE.copy(deep=True)

La variable YYYYMM contiene los años y los meses desde 1949 hasta 2021. Sin embargo, esta variable es una variable numérica, por lo tanto debemos convertirla en string para poder separar los años de los meses.

In [4]:
RE2['YYYYMM']=RE2['YYYYMM'].astype(str)
RE2['YEAR']=RE2['YYYYMM'].str[0:4]
RE2['MONTH']=RE2['YYYYMM'].str[4:6]
RE2.head(10)

,MSN,YYYYMM,Value,Column_Order,Description,Unit,YEAR,MONTH
0,WDPRBUS,194913,1549.262,1,Wood Energy Production,Trillion Btu,1949,13
1,WDPRBUS,195013,1562.307,1,Wood Energy Production,Trillion Btu,1950,13
2,WDPRBUS,195113,1534.669,1,Wood Energy Production,Trillion Btu,1951,13
3,WDPRBUS,195213,1474.369,1,Wood Energy Production,Trillion Btu,1952,13
4,WDPRBUS,195313,1418.601,1,Wood Energy Production,Trillion Btu,1953,13
5,WDPRBUS,195413,1394.327,1,Wood Energy Production,Trillion Btu,1954,13
6,WDPRBUS,195513,1424.143,1,Wood Energy Production,Trillion Btu,1955,13
7,WDPRBUS,195613,1415.871,1,Wood Energy Production,Trillion Btu,1956,13
8,WDPRBUS,195713,1333.581,1,Wood Energy Production,Trillion Btu,1957,13
9,WDPRBUS,195813,1323.123,1,Wood Energy Production,Trillion Btu,1958,13

Posteriormente, convertimos las variables "MONTH" y "YEAR" en variables numéricas nuevamente y, se observa que en la variable "MONTH" existen valores desde el 1 hasta el 13, haciendo referencia a los 12 meses del año y, el valor 13 se refiere al valor anual. Por ello, eliminamos todas las observaciones mensuales para quedarnos solo con los valores anuales (MONTH=13). Asimismo, eliminamos columnas que no son de nuestro interés.

In [5]:
RE2['MONTH']=RE2['MONTH'].astype(int)
RE2['YEAR']=RE2['YEAR'].astype(int)
RE2.drop(RE2.index[RE2.MONTH <= 12], axis=0, inplace=True)
RE2.drop(['MSN','Column_Order','Unit', 'MONTH', 'YYYYMM'], axis=1)

          Value                         Description  YEAR
0      1549.262              Wood Energy Production  1949
1      1562.307              Wood Energy Production  1950
2      1534.669              Wood Energy Production  1951
3      1474.369              Wood Energy Production  1952
4      1418.601              Wood Energy Production  1953
...         ...                                 ...   ...
8503  10390.662  Total Renewable Energy Consumption  2016
8516  11115.512  Total Renewable Energy Consumption  2017
8529  11342.541  Total Renewable Energy Consumption  2018
8542  11436.136  Total Renewable Energy Consumption  2019
8555  11502.822  Total Renewable Energy Consumption  2020

[936 rows x 3 columns]

Las base de datos está en formato "long", por ello, para visualizar mejor los datos, se transforma la base de datos aun formato "wide". Con esta transformación podemos observar que hay años donde no se tiene información sobre el consumo y producción de energía renovables por fuentes.

In [6]:
RE2=RE2.pivot(index='Description', columns='YEAR', values='Value')
RE2.head(10)

YEAR,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Description,,,,,,,,,,,,,,,,,,,,,
Biofuels Consumption,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,1941.48,1899.134,2022,2089.207,2170.219,2313.107,2338.66,2324.231,2340.758,2099.902
Biofuels Production,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,2037.424,1935.741,1995.759,2125.785,2186.681,2309.235,2381.148,2439.807,2396.117,2158.509
Geothermal Energy Consumption,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,212.311,211.592,214.006,214.49,211.836,209.604,210.233,208.865,201.285,202.9
Hydroelectric Power Consumption,1424.722,1415.411,1423.795,1465.812,1412.859,1359.772,1359.844,1434.711,1515.613,1591.967,...,3102.852,2628.702,2562.382,2466.577,2321.177,2472.442,2766.967,2663.138,2563.516,2502.708
Solar Energy Consumption,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,112.429,158.961,224.524,337.421,426.734,570.218,776.925,915.105,1017.111,1211.452
Total Biomass Energy Consumption,1549.262,1562.307,1534.669,1474.369,1418.601,1394.327,1424.143,1415.871,1333.581,1323.123,...,4616.493,4516.951,4856.691,5006.162,5000.358,5042.803,5018.496,5073.068,5019.391,4621.031
Total Biomass Energy Production,1549.262,1562.307,1534.669,1474.369,1418.601,1394.327,1424.143,1415.871,1333.581,1323.123,...,4712.436,4553.559,4830.451,5042.74,5016.82,5111.507,5139.61,5282.702,5178.394,4785.672
Total Renewable Energy Consumption,2973.984,2977.718,2958.464,2940.181,2831.46,2754.099,2783.987,2850.582,2849.194,2915.09,...,9211.72,8856.265,9458.962,9752.19,9737.412,10390.662,11115.512,11342.541,11436.136,11502.822
Total Renewable Energy Production,2973.984,2977.718,2958.464,2940.181,2831.46,2754.099,2783.987,2850.582,2849.194,2915.09,...,9307.664,8892.873,9432.722,9788.768,9753.873,10459.366,11236.626,11552.175,11595.138,11667.463
Waste Energy Consumption,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,461.793,466.604,496.436,515.877,518.371,503.219,495.26,487.347,442.447,439.734

En seguida, como se quiere analizar solo el consumo de energías renovables, se procede a eliminar todas las variables relacionadas a la producción de energías renovables.

In [7]:
RE2.drop(["Biofuels Production","Total Biomass Energy Production", "Total Renewable Energy Production", "Wood Energy Production"], inplace=True)
RE2

YEAR,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Description,,,,,,,,,,,,,,,,,,,,,
Biofuels Consumption,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,1941.48,1899.134,2022,2089.207,2170.219,2313.107,2338.66,2324.231,2340.758,2099.902
Geothermal Energy Consumption,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,212.311,211.592,214.006,214.49,211.836,209.604,210.233,208.865,201.285,202.9
Hydroelectric Power Consumption,1424.722,1415.411,1423.795,1465.812,1412.859,1359.772,1359.844,1434.711,1515.613,1591.967,...,3102.852,2628.702,2562.382,2466.577,2321.177,2472.442,2766.967,2663.138,2563.516,2502.708
Solar Energy Consumption,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,112.429,158.961,224.524,337.421,426.734,570.218,776.925,915.105,1017.111,1211.452
Total Biomass Energy Consumption,1549.262,1562.307,1534.669,1474.369,1418.601,1394.327,1424.143,1415.871,1333.581,1323.123,...,4616.493,4516.951,4856.691,5006.162,5000.358,5042.803,5018.496,5073.068,5019.391,4621.031
Total Renewable Energy Consumption,2973.984,2977.718,2958.464,2940.181,2831.46,2754.099,2783.987,2850.582,2849.194,2915.09,...,9211.72,8856.265,9458.962,9752.19,9737.412,10390.662,11115.512,11342.541,11436.136,11502.822
Waste Energy Consumption,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,461.793,466.604,496.436,515.877,518.371,503.219,495.26,487.347,442.447,439.734
Wind Energy Consumption,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,1167.636,1340.059,1601.359,1727.542,1777.306,2095.595,2342.891,2482.364,2634.834,2964.731
Wood Energy Consumption,1549.262,1562.307,1534.669,1474.369,1418.601,1394.327,1424.143,1415.871,1333.581,1323.123,...,2213.22,2151.213,2338.256,2401.078,2311.768,2226.478,2184.576,2261.49,2236.187,2081.395

Asimismo, para el gráfico solo se tomarán 4 energías renovables, por lo que las siguientes: Hidroeléctrica, Solar, Eólica y Biomasa. Estas cuatro variables son renombradas para acortar sus nombres originales.

In [8]:
RE2.rename(index={"Hydroelectric Power Consumption":"Hydroelectric Power","Solar Energy Consumption":"Solar","Wind Energy Consumption":"Wind","Total Biomass Energy Consumption":"Biomass"}, inplace=True)
RE2

YEAR,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
Description,,,,,,,,,,,,,,,,,,,,,
Biofuels Consumption,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,1941.48,1899.134,2022,2089.207,2170.219,2313.107,2338.66,2324.231,2340.758,2099.902
Geothermal Energy Consumption,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,212.311,211.592,214.006,214.49,211.836,209.604,210.233,208.865,201.285,202.9
Hydroelectric Power,1424.722,1415.411,1423.795,1465.812,1412.859,1359.772,1359.844,1434.711,1515.613,1591.967,...,3102.852,2628.702,2562.382,2466.577,2321.177,2472.442,2766.967,2663.138,2563.516,2502.708
Solar,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,112.429,158.961,224.524,337.421,426.734,570.218,776.925,915.105,1017.111,1211.452
Biomass,1549.262,1562.307,1534.669,1474.369,1418.601,1394.327,1424.143,1415.871,1333.581,1323.123,...,4616.493,4516.951,4856.691,5006.162,5000.358,5042.803,5018.496,5073.068,5019.391,4621.031
Total Renewable Energy Consumption,2973.984,2977.718,2958.464,2940.181,2831.46,2754.099,2783.987,2850.582,2849.194,2915.09,...,9211.72,8856.265,9458.962,9752.19,9737.412,10390.662,11115.512,11342.541,11436.136,11502.822
Waste Energy Consumption,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,461.793,466.604,496.436,515.877,518.371,503.219,495.26,487.347,442.447,439.734
Wind,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,...,1167.636,1340.059,1601.359,1727.542,1777.306,2095.595,2342.891,2482.364,2634.834,2964.731
Wood Energy Consumption,1549.262,1562.307,1534.669,1474.369,1418.601,1394.327,1424.143,1415.871,1333.581,1323.123,...,2213.22,2151.213,2338.256,2401.078,2311.768,2226.478,2184.576,2261.49,2236.187,2081.395

Para darle un formato de series de tiempo, se transpone la base de datos.

In [9]:
RE2=RE2.transpose()
RE2.head(5)

Description,Biofuels Consumption,Geothermal Energy Consumption,Hydroelectric Power,Solar,Biomass,Total Renewable Energy Consumption,Waste Energy Consumption,Wind,Wood Energy Consumption
YEAR,,,,,,,,,
1949,Not Available,Not Available,1424.722,Not Available,1549.262,2973.984,Not Available,Not Available,1549.262
1950,Not Available,Not Available,1415.411,Not Available,1562.307,2977.718,Not Available,Not Available,1562.307
1951,Not Available,Not Available,1423.795,Not Available,1534.669,2958.464,Not Available,Not Available,1534.669
1952,Not Available,Not Available,1465.812,Not Available,1474.369,2940.181,Not Available,Not Available,1474.369
1953,Not Available,Not Available,1412.859,Not Available,1418.601,2831.46,Not Available,Not Available,1418.601

Como se mencionó anteriormente, solo se quiere graficar el consumo de 4 tipos de energías renovables, por lo que se eliminan las otras columnas que contienen energías no relevantes para el análisis: biocombustible, geotérmica, residuos sólidos, entre otros.

In [10]:
RE2.drop(['Biofuels Consumption','Geothermal Energy Consumption','Total Renewable Energy Consumption','Waste Energy Consumption','Wood Energy Consumption'], axis=1, inplace=True )

Ya tenemos los datos relevantes para nuestro análisis, y se observa que la variable YEAR se encuentra como un índice. Esto, no permitirá realizar el gráfico.

In [11]:
RE2

Description Hydroelectric Power          Solar   Biomass           Wind
YEAR
1949                   1424.722  Not Available  1549.262  Not Available
1950                   1415.411  Not Available  1562.307  Not Available
1951                   1423.795  Not Available  1534.669  Not Available
1952                   1465.812  Not Available  1474.369  Not Available
1953                   1412.859  Not Available  1418.601  Not Available
...                         ...            ...       ...            ...
2016                   2472.442        570.218  5042.803       2095.595
2017                   2766.967        776.925  5018.496       2342.891
2018                   2663.138        915.105  5073.068       2482.364
2019                   2563.516       1017.111  5019.391       2634.834
2020                   2502.708       1211.452  4621.031       2964.731

[72 rows x 4 columns]

Para corregir este problema, utilizamos el comando reset_index. Con ello, recuperamos la variable YEAR y tenemos los datos del consumo de energías renovables en una sola columna. Ello facilitará la elaboración del gráfico.

In [12]:
data=RE2.reset_index().melt("YEAR")
data

     YEAR          Description     value
0    1949  Hydroelectric Power  1424.722
1    1950  Hydroelectric Power  1415.411
2    1951  Hydroelectric Power  1423.795
3    1952  Hydroelectric Power  1465.812
4    1953  Hydroelectric Power  1412.859
..    ...                  ...       ...
283  2016                 Wind  2095.595
284  2017                 Wind  2342.891
285  2018                 Wind  2482.364
286  2019                 Wind  2634.834
287  2020                 Wind  2964.731

[288 rows x 3 columns]

Por último, antes de realizar el gráfico se observa que existen missing values llamados "Not Available". Por ello, se eliminan las observaciones que tengan este nombre. Esta decisión es la más adecuada, dado que algunas tecnologías no existían en años anteriores, como el caso de la energía solar durante el siglo pasado.

In [13]:
data.drop(data[data["value"]=="Not Available"].index, inplace=True)

Con la base de datos limpia, se puede realizar el gráfico del consumo de energías renovables en los Estados Unidos desde 1949 hasta el año 2020.

In [14]:
alt.Chart(data).mark_line().encode(
    x=alt.X('YEAR:N', title="Year"),
    y=alt.Y('value:Q', title="Trillion BTU"),
    color=alt.Color('Description')
    ).interactive().properties(
    title={
      "text": ["Renewable Energy Consumption"], 
      "subtitle": ["Source: U.S. Energy Information Administration"],
      "color": "Black",
      "subtitleColor": "Black"
    })

alt.Chart(...)

En el gráfico se observa que el consumo de energía hidroeléctrica está decreciendo desde el año 2000 en comparación al periodo entre 1980 a 1999. Asimismo, se observa que la biomasa el consumo de energía de biomasa está en constante crecimiento desde la decada de 1970, aunque en los últimos años, se estancó en los mismo niveles. Finalmente, se observa que el consumo las energías solar y eólica están en rápido crecimiento desde inicios de este siglo, debido, principalmente a que son fuentes de energía cada vez más baratas a causa del desarrollo tecnológico que permite que el costo de producción sea más bajo.